### PR TITLE
Remove tag related features from `add` and `edit` 

### LINKED ISSUE #127: [PE-D] Adding tag with add command vs adding via tag command
Adding tags via the add command will generate the tag without the value, however adding tags via the tag command generates the tag with the value. In the event there is an existing tag added via the add command, and the tag command is called with the exact same tag name and a value, the original tag is overwritten with the new tag and value.

Not sure if this is an intended result here.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: cheweejia/ped#10

### LINKED ISSUE #132: [PE-D] Telemarketers can edit and remove tags with Supervisor-level permissions
Steps to reproduce:
1. Promote self to Supervisor using `profile` command. (e.g `profile -n John -rol Supervisor`)
2. Aa Supervisor, add a valid tag command to persons in the list with `-s` flag at the end.

3. Demote self to Telemarketer using `profile` command. (e.g `profile -n John -rol Telemarketer`)
4. Edit the tag using `edit INDEX -t TAGNAME`, or remove the tag using `edit INDEX -t`

This goes against intended behaviour of only Supervisors being allowed to remove edit/tags with Supervisor-level permissions.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: atyhamos/ped#12

### LINKED ISSUE #159: Remove ability to add and edit tags via the `add` and `edit` commands

### PR DESCRIPTION
**Pull request by skythefire**
Resolves #159 & #127
Fixes #132 

Removes tagging features from the `add` and `edit` command

Minor UG updates

### CODE REVIEW

File: src/main/java/teletubbies/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -25,18 +24,15 @@
...
-            + PREFIX_ADDRESS + "311, Clementi Ave 2, #02-25 "
-            + PREFIX_TAG + "friends "
-            + PREFIX_TAG + "owesMoney";
+            + PREFIX_NAME + " John Doe "
+            + PREFIX_PHONE + " 98765432 "
+            + PREFIX_EMAIL + " johnd@example.com "
+            + PREFIX_ADDRESS + " 311, Clementi Ave 2, #02-25 ";
 
     public static final String MESSAGE_SUCCESS = "New person added: %1$s";
     public static final String MESSAGE_DUPLICATE_PERSON = "This person already exists in the address book";
```
Comment (gok99) [inline src/main/java/teletubbies/logic/commands/AddCommand.java:38]: Should we keep calling it an address book?

**Review by gok99 — APPROVED** [review]
LGTM
